name: SonarCloud analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create sonar-project.properties
        run: |
          cat > ${{ github.workspace }}/sonar-project.properties << EOF
          sonar.projectKey=juangg11_Walter-Red-Social
          sonar.organization=juangg11
          EOF
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ github.workspace }}
